Rework the system of environment variables configurations

diff --git a/znuny/zcli b/znuny/zcli
--- a/znuny/zcli
+++ b/znuny/zcli
@@ -36,6 +36,7 @@ zcli_usage() {
   printf "%s\n" "Commands:"
   printf "  %s   Manage the configuration of znuny\n" "config  "
   printf "  %s   Check some features or resources\n" "check   "
+  printf "  %s   Development command to test features\n" "dev     "
   printf "  %s   Download the znuny archive\n" "download"
   printf "  %s   Initialize the container\n" "init    "
   printf "  %s   Run Znuny\n" "run     "
@@ -430,6 +431,35 @@ zcli_check_config_usage() {
   printf "%s\n" "Usage:"
   printf "  zcli check config\n"
   printf "  zcli check config --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+zcli_dev_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "zcli dev - Development command to test features\n"
+    echo
+
+  else
+    printf "zcli dev - Development command to test features\n"
+    echo
+
+  fi
+
+  printf "%s\n" "Usage:"
+  printf "  zcli dev\n"
+  printf "  zcli dev --help | -h\n"
   echo
 
   # :command.long_usage
@@ -1090,6 +1120,129 @@ EOF
 )
 }
 
+function gen_add_customers() {
+  CONTENT=$(cat << EOF | tee -a ${CONFIG_PATH}
+    \$Self->{CustomerUser1} = {
+        Name => 'LDAP Backend',
+        Module => 'Kernel::System::CustomerUser::LDAP',
+        Params => {
+            # ldap host
+            Host => 'bay.csuhayward.edu',
+            # ldap base dn
+            BaseDN => 'ou=seas,o=csuh',
+            # search scope (one|sub)
+            SSCOPE => 'sub',
+            # The following is valid but would only be necessary if the
+            # anonymous user does NOT have permission to read from the LDAP tree
+            UserDN => '',
+            UserPw => '',
+            # in case you want to add always one filter to each ldap query, use
+            # this option. e. g. AlwaysFilter => '(mail=*)' or AlwaysFilter => '(objectclass=user)'
+            AlwaysFilter => '',
+            # if the charset of your ldap server is iso-8859-1, use this:
+            # SourceCharset => 'iso-8859-1',
+            # die if backend can't work, e. g. can't connect to server
+            Die => 0,
+            # Net::LDAP new params (if needed - for more info see perldoc Net::LDAP)
+            Params => {
+                port    => 389,
+                timeout => 120,
+                async   => 0,
+                version => 3,
+            },
+        },
+        # customer unique id
+        CustomerKey => 'uid',
+        # customer #
+        CustomerID => 'mail',
+        CustomerUserListFields => ['cn', 'mail'],
+        CustomerUserSearchFields => ['uid', 'cn', 'mail'],
+        CustomerUserSearchPrefix => '',
+        CustomerUserSearchSuffix => '*',
+        CustomerUserSearchListLimit => 250,
+        CustomerUserPostMasterSearchFields => ['mail'],
+        CustomerUserNameFields => ['givenname', 'sn'],
+        # Configures the character for joining customer user name parts. Join single space if it is not defined.
+        CustomerUserNameFieldsJoin => '',
+        # show customer user and customer tickets in customer interface
+        CustomerUserExcludePrimaryCustomerID => 0,
+        # add a ldap filter for valid users (expert setting)
+        # CustomerUserValidFilter => '(!(description=locked))',
+        # admin can't change customer preferences
+        AdminSetPreferences => 0,
+        # cache time to live in sec. - cache any ldap queries
+        CacheTTL => 0,
+        Map => [
+            # note: Login, Email and CustomerID needed!
+            # var, frontend, storage, shown (1=always,2=lite), required, storage-type, http-link, readonly, http-link-target, link class(es)
+            [ 'UserTitle',       Translatable('Title or salutation'), 'title',               1, 0, 'var', '', 1, undef, undef ],
+            [ 'UserFirstname',   Translatable('Firstname'),           'givenname',           1, 1, 'var', '', 1, undef, undef ],
+            [ 'UserLastname',    Translatable('Lastname'),            'sn',                  1, 1, 'var', '', 1, undef, undef ],
+            [ 'UserLogin',       Translatable('Username'),            'uid',                 1, 1, 'var', '', 1, undef, undef ],
+            [ 'UserEmail',       Translatable('Email'),               'mail',                1, 1, 'var', '', 1, undef, undef ],
+            [ 'UserCustomerID',  Translatable('CustomerID'),          'mail',                0, 1, 'var', '', 1, undef, undef ],
+            # [ 'UserCustomerIDs', Translatable('CustomerIDs'),         'second_customer_ids', 1, 0, 'var', '', 1, undef, undef ],
+            [ 'UserPhone',       Translatable('Phone'),               'telephonenumber',     1, 0, 'var', '', 1, undef, undef ],
+            [ 'UserAddress',     Translatable('Address'),             'postaladdress',       1, 0, 'var', '', 1, undef, undef ],
+            [ 'UserComment',     Translatable('Comment'),             'description',         1, 0, 'var', '', 1, undef, undef ],
+
+            # this is needed, if "SMIME::FetchFromCustomer" is active
+            # [ 'UserSMIMECertificate', 'SMIMECertificate', 'userSMIMECertificate', 0, 1, 'var', '', 1, undef, undef ],
+
+            # Dynamic field example
+            # [ 'DynamicField_Name_X', undef, 'Name_X', 0, 0, 'dynamic_field', undef, 0, undef, undef ],
+        ],
+    };
+
+    \$Self->{'Customer::AuthModule1'} = 'Kernel::System::CustomerAuth::LDAP';
+    \$Self->{'Customer::AuthModule::LDAP::Host1'} = 'ldap.example.com';
+    \$Self->{'Customer::AuthModule::LDAP::BaseDN1'} = 'dc=example,dc=com';
+    \$Self->{'Customer::AuthModule::LDAP::UID1'} = 'uid';
+
+# Check if the user is allowed to auth in a posixGroup
+# (e. g. user needs to be in a group xyz to use Znuny)
+    \$Self->{'Customer::AuthModule::LDAP::GroupDN1'} = 'cn=znuny-allow,ou=posixGroups,dc=example,dc=com';
+    \$Self->{'Customer::AuthModule::LDAP::AccessAttr1'} = 'memberUid';
+
+# for ldap posixGroups objectclass (just uid)
+    \$Self->{'Customer::AuthModule::LDAP::UserAttr1'} = 'UID';
+
+# for non ldap posixGroups objectclass (full user dn)
+    \$Self->{'Customer::AuthModule::LDAP::UserAttr1'} = 'DN';
+
+# The following is valid but would only be necessary if the
+# anonymous user do NOT have permission to read from the LDAP tree
+    \$Self->{'Customer::AuthModule::LDAP::SearchUserDN1'} = '';
+    \$Self->{'Customer::AuthModule::LDAP::SearchUserPw1'} = '';
+
+# in case you want to add always one filter to each ldap query, use
+# this option. e. g. AlwaysFilter => '(mail=*)' or AlwaysFilter => '(objectclass=user)'
+    \$Self->{'Customer::AuthModule::LDAP::AlwaysFilter1'} = '';
+
+# in case you want to add a suffix to each customer login name, then
+# you can use this option. e. g. user just want to use user but
+# in your ldap directory exists user@domain.
+    \$Self->{'Customer::AuthModule::LDAP::UserSuffix1'} = '@domain.com';
+
+# Net::LDAP new params (if needed - for more info see perldoc Net::LDAP)
+    \$Self->{'Customer::AuthModule::LDAP::Params1'} = {
+        port    => 389,
+        timeout => 120,
+        async   => 0,
+        version => 3,
+    };
+
+EOF
+)
+}
+
+function gen_add_agents() {
+  CONTENT=$(cat << EOF | tee -a ${CONFIG_PATH}
+
+EOF
+)
+}
+
 function gen_add_return() {
   CONTENT=$(cat << EOF | tee -a ${CONFIG_PATH}
     return 1;
@@ -1148,26 +1301,28 @@ zcli_config_apache_command() {
   customLogger "info" "config_apache" "Create the virtualhost to expose Znuny"
   ln -s /opt/otrs/scripts/apache2-httpd.include.conf /etc/apache2/conf-available/zzz_znuny.conf || true
 
-  customLogger "info" "config_apache" "Enable the rewrite engine"
-  for i in {1..9}; do
-    COMPOSED_VAR="ZNUNY_APACHE_REWRITE_RULE_${i}"
-    if [[ ! -z ${!COMPOSED_VAR} ]]; then
-      echo -e "\n###\n#Add custom rewrite rules\n###" >> /etc/apache2/conf-available/zzz_znuny.conf
-      echo "<IfModule mod_rewrite.c>" >> /etc/apache2/conf-available/zzz_znuny.conf
-      echo "    RewriteEngine on" >> /etc/apache2/conf-available/zzz_znuny.conf
-      echo "</IfModule>" >> /etc/apache2/conf-available/zzz_znuny.conf
-      echo -e "\n" >> /etc/apache2/conf-available/zzz_znuny.conf
-      break
-    fi
-  done
+  # customLogger "info" "config_apache" "Enable the rewrite engine"
+  # for i in {1..9}; do
+  #   COMPOSED_VAR="ZNUNY_APACHE_REWRITE_RULE_${i}"
+  #   if [[ ! -z ${!COMPOSED_VAR} ]]; then
+  #     break
+  #   fi
+  # done
 
-  customLogger "info" "config_apache" "Add the rewrite rules"
-  for i in {9..1}; do
-    COMPOSED_VAR="ZNUNY_APACHE_REWRITE_RULE_${i}"
-    if [[ ! -z ${!COMPOSED_VAR} ]]; then
-      sed -i '/RewriteEngine on/a\ \ \ \ \ \ \ \ '"${!COMPOSED_VAR}"'' /etc/apache2/conf-available/zzz_znuny.conf
-    fi
-  done
+  customLogger "info" "config_apache" "Enable then add rewrite rules"
+  if [[ ! -z ${ZNUNY_APACHE_REWRITE_RULES} ]]; then
+    echo -e "\n###\n#Add custom rewrite rules\n###" >> /etc/apache2/conf-available/zzz_znuny.conf
+    echo "<IfModule mod_rewrite.c>" >> /etc/apache2/conf-available/zzz_znuny.conf
+    echo "    RewriteEngine on" >> /etc/apache2/conf-available/zzz_znuny.conf
+
+    while IFS= read -r RULE; do
+      echo "        ${RULE}" >> /etc/apache2/conf-available/zzz_znuny.conf
+    done <<< "${ZNUNY_APACHE_REWRITE_RULES}"
+    # sed -i '/RewriteEngine on/a\ \ \ \ \ \ \ \ '"${!COMPOSED_VAR}"'' /etc/apache2/conf-available/zzz_znuny.conf
+
+    echo "</IfModule>" >> /etc/apache2/conf-available/zzz_znuny.conf
+    echo -e "\n" >> /etc/apache2/conf-available/zzz_znuny.conf
+  fi
 
   customLogger "info" "config_apache" "Enable required Apache modules - Part 1"
   a2enmod perl headers deflate filter cgi 2>&1>/dev/null
@@ -1327,6 +1482,21 @@ zcli_check_config_command() {
 }
 
 # :command.function
+zcli_dev_command() {
+  # src/dev_command.sh
+    # customLogger "warn" "env" "Failed to load the environment variable ZNUNY_USER_ADMIN_PASSWORD"
+    #
+    LCTT=0
+    echo -e "${ZNUNY_TEST_VAR}" > /test-file.env
+
+    for LINES in $(echo -e "${ZNUNY_TEST_VAR}"); do
+      LCTT=$((LCTT+1))
+      echo -e "${LCTT}: ${LINES}" >> /test_var
+    done
+
+}
+
+# :command.function
 zcli_download_command() {
   # src/download_command.sh
   DESTINATION="/tmp/znuny-${CONFIG_ZNUNY_VERSION}.tar.gz"
@@ -1373,9 +1543,11 @@ zcli_init_command() {
 
   zcli user admin
 
+  zcli dev
+
   zcli run
 
-  sleep 1000000
+  # sleep 1000000
 
 }
 
@@ -1463,6 +1635,13 @@ parse_requirements() {
       action="check"
       shift
       zcli_check_parse_requirements "$@"
+      shift $#
+      ;;
+
+    dev)
+      action="dev"
+      shift
+      zcli_dev_parse_requirements "$@"
       shift $#
       ;;
 
@@ -2059,6 +2238,50 @@ zcli_check_config_parse_requirements() {
 }
 
 # :command.parse_requirements
+zcli_dev_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        zcli_dev_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="dev"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
 zcli_download_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
@@ -2437,6 +2660,7 @@ run() {
     "check") zcli_check_command ;;
     "check modules") zcli_check_modules_command ;;
     "check config") zcli_check_config_command ;;
+    "dev") zcli_dev_command ;;
     "download") zcli_download_command ;;
     "init") zcli_init_command ;;
     "run") zcli_run_command ;;
