feat: create two upgrade subcommand (#2)
job: download and install znuny, then proceed to do the database upgrade
shell: proceed to do the database upgrade immediately

Co-authored-by: Aurore Roma <aurore.roma@atos.net>

diff --git a/znuny/zcli b/znuny/zcli
--- a/znuny/zcli
+++ b/znuny/zcli
@@ -55,6 +55,8 @@ zcli_usage() {
   [[ -n $long_usage ]] && printf "  %s   Run the daemon of Znuny\n" "run daemon        "
   [[ -n $long_usage ]] && printf "  %s   Run Znuny\n" "run znuny         "
   printf "  %s   Manage Upgrades operations\n" "upgrade           "
+  [[ -n $long_usage ]] && printf "  %s   Upgrade database\n" "upgrade shell     "
+  [[ -n $long_usage ]] && printf "  %s   Download znuny then upgrade database\n" "upgrade job       "
   printf "  %s   Manage users\n" "user              "
   [[ -n $long_usage ]] && printf "  %s   Create the admin user\n" "user admin        "
   [[ -n $long_usage ]] && printf "  %s   Set the user permissions\n" "user permissions  "
@@ -1028,8 +1030,71 @@ zcli_upgrade_usage() {
   fi
 
   printf "%s\n" "Usage:"
-  printf "  zcli upgrade\n"
-  printf "  zcli upgrade --help | -h\n"
+  printf "  zcli upgrade COMMAND\n"
+  printf "  zcli upgrade [COMMAND] --help | -h\n"
+  echo
+  # :command.usage_commands
+  printf "%s\n" "Commands:"
+  printf "  %s   Upgrade database\n" "shell"
+  printf "  %s   Download znuny then upgrade database\n" "job  "
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+zcli_upgrade_shell_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "zcli upgrade shell - Upgrade database\n"
+    echo
+
+  else
+    printf "zcli upgrade shell - Upgrade database\n"
+    echo
+
+  fi
+
+  printf "%s\n" "Usage:"
+  printf "  zcli upgrade shell\n"
+  printf "  zcli upgrade shell --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+zcli_upgrade_job_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "zcli upgrade job - Download znuny then upgrade database\n"
+    echo
+
+  else
+    printf "zcli upgrade job - Download znuny then upgrade database\n"
+    echo
+
+  fi
+
+  printf "%s\n" "Usage:"
+  printf "  zcli upgrade job\n"
+  printf "  zcli upgrade job --help | -h\n"
   echo
 
   # :command.long_usage
@@ -2399,8 +2464,19 @@ zcli_run_znuny_command() {
 }
 
 # :command.function
-zcli_upgrade_command() {
-  # src/upgrade_command.sh
+zcli_upgrade_shell_command() {
+  # src/upgrade_shell_command.sh
+  zcli check modules
+
+  zcli check config
+
+  su -c "/opt/otrs/scripts/MigrateToZnuny6_5.pl" -s /bin/sh otrs
+
+}
+
+# :command.function
+zcli_upgrade_job_command() {
+  # src/upgrade_job_command.sh
   zcli download
 
   zcli user system
@@ -3884,7 +3960,125 @@ zcli_upgrade_parse_requirements() {
   done
 
   # :command.command_filter
-  action="upgrade"
+  action=${1:-}
+
+  case $action in
+    -*) ;;
+
+    shell)
+      action="shell"
+      shift
+      zcli_upgrade_shell_parse_requirements "$@"
+      shift $#
+      ;;
+
+    job)
+      action="job"
+      shift
+      zcli_upgrade_job_parse_requirements "$@"
+      shift $#
+      ;;
+
+    # :command.command_fallback
+    "")
+      zcli_upgrade_usage >&2
+      exit 1
+      ;;
+
+    *)
+      printf "invalid command: %s\n" "$action" >&2
+      exit 1
+      ;;
+
+  esac
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+zcli_upgrade_shell_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        zcli_upgrade_shell_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="upgrade shell"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+zcli_upgrade_job_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        zcli_upgrade_job_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="upgrade job"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -4167,6 +4361,8 @@ run() {
     "run daemon") zcli_run_daemon_command ;;
     "run znuny") zcli_run_znuny_command ;;
     "upgrade") zcli_upgrade_command ;;
+    "upgrade shell") zcli_upgrade_shell_command ;;
+    "upgrade job") zcli_upgrade_job_command ;;
     "user") zcli_user_command ;;
     "user admin") zcli_user_admin_command ;;
     "user permissions") zcli_user_permissions_command ;;
