Fix the version 6.5.4 of the docker-znuny image

diff --git a/znuny/zcli b/znuny/zcli
--- a/znuny/zcli
+++ b/znuny/zcli
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.0.7 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.1.1 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -1240,99 +1240,63 @@ EOF
 }
 
 # src/lib/config.sh
-config_init() {
-  CONFIG_FILE=${CONFIG_FILE:=config.ini}
-  [[ -f "$CONFIG_FILE" ]] || touch "$CONFIG_FILE"
+
+config_show() {
+  config_load
+  ini_show
 }
 
 config_get() {
-  local key=$1
-  local regex="^$key *= *(.+)$"
-  local value=""
+  local key="$1"
+  local default_value="$2"
 
-  config_init
-
-  while IFS= read -r line || [ -n "$line" ]; do
-    if [[ $line =~ $regex ]]; then
-      value="${BASH_REMATCH[1]}"
-      break
-    fi
-  done <"$CONFIG_FILE"
-
-  echo "$value"
+  config_load
+  echo "${ini["$key"]:-$default_value}"
 }
 
 config_set() {
-  local key=$1
+  local key="$1"
   shift
   local value="$*"
 
-  config_init
-
-  local regex="^($key) *= *.+$"
-  local output=""
-  local found_key=""
-  local newline
-
-  while IFS= read -r line || [ -n "$line" ]; do
-    newline=$line
-    if [[ $line =~ $regex ]]; then
-      found_key="${BASH_REMATCH[1]}"
-      newline="$key = $value"
-      output="$output$newline\n"
-    elif [[ $line ]]; then
-      output="$output$line\n"
-    fi
-  done <"$CONFIG_FILE"
-
-  if [[ -z $found_key ]]; then
-    output="$output$key = $value\n"
-  fi
-
-  printf "%b\n" "$output" >"$CONFIG_FILE"
+  config_load
+  ini["$key"]="$value"
+  config_save
 }
 
 config_del() {
-  local key=$1
+  local key="$1"
 
-  local regex="^($key) *="
-  local output=""
-
-  config_init
-
-  while IFS= read -r line || [ -n "$line" ]; do
-    if [[ $line ]] && [[ ! $line =~ $regex ]]; then
-      output="$output$line\n"
-    fi
-  done <"$CONFIG_FILE"
-
-  printf "%b\n" "$output" >"$CONFIG_FILE"
-}
-
-config_show() {
-  config_init
-  cat "$CONFIG_FILE"
+  config_load
+  unset "ini[$key]"
+  config_save
 }
 
 config_keys() {
-  local regex="^([a-zA-Z0-9_\-\/\.]+) *="
-
-  config_init
-
-  local keys=()
-  local key
-
-  while IFS= read -r line || [ -n "$line" ]; do
-    if [[ $line =~ $regex ]]; then
-      key="${BASH_REMATCH[1]}"
-      keys+=("$key")
-    fi
-  done <"$CONFIG_FILE"
-  echo "${keys[@]}"
+  config_load
+  ini_keys
 }
 
 config_has_key() {
   [[ $(config_get "$1") ]]
+}
+
+config_reload() {
+  declare -g config_loaded=false
+  config_load
+}
+
+config_load() {
+  [[ "$config_loaded" == "true" ]] && return
+
+  declare -g CONFIG_FILE=${CONFIG_FILE:=config.ini}
+  declare -g config_loaded=true
+  [[ -f "$CONFIG_FILE" ]] || touch "$CONFIG_FILE"
+  ini_load "$CONFIG_FILE"
+}
+
+config_save() {
+  ini_save "$CONFIG_FILE"
 }
 
 # src/lib/database.sh
@@ -1402,6 +1366,33 @@ function database_init_pgsql() {
   psql -q -h ${HOST} -p${PORT} -U ${USER} -d ${NAME} -f /opt/otrs/scripts/database/schema-post.postgresql.sql
 }
 
+function database_wait_pgsql() {
+  HOST=${1}
+  PORT=${2}
+  NAME=${3}
+  USER=${4}
+  PASSWORD=${5}
+
+  export PGPASSWORD=${PASSWORD}
+
+  for i in {1..60}; do
+    pg_isready -q -h ${HOST} -p ${PORT} -U ${USER} -d ${NAME}
+
+    if [[ ${?} -eq 0 ]]; then
+      CHECK="true"
+      break
+    else
+      sleep 1
+    fi
+  done
+
+  if [[ ${CHECK} == "true" ]]; then
+    return 0 # Database already initialize
+  else
+    return 1 # Database not initialize
+  fi
+}
+
 # src/lib/env.sh
 function set_env_database() {
   if [[ -z ${ZNUNY_DATABASE_HOST} ]]; then
@@ -1464,6 +1455,83 @@ function set_env_mailing() {
       exit 1
     fi
   fi
+}
+
+# src/lib/ini.sh
+
+ini_load() {
+  declare -gA ini
+
+  local ini_file="$1"
+
+  local section=""
+  local key=""
+  local value=""
+  local section_regex="^\[(.+)\]"
+  local key_regex="^([^ =]+) *= *(.*) *$"
+  local comment_regex="^;"
+
+  while IFS= read -r line; do
+    if [[ $line =~ $comment_regex ]]; then
+      continue
+    elif [[ $line =~ $section_regex ]]; then
+      section="${BASH_REMATCH[1]}."
+    elif [[ $line =~ $key_regex ]]; then
+      key="${BASH_REMATCH[1]}"
+      value="${BASH_REMATCH[2]}"
+      [[ $value == *\$* ]] && eval "value=\"$value\""
+      ini["${section}${key}"]="$value"
+    fi
+  done <"$ini_file"
+}
+
+ini_save() {
+  declare -gA ini
+
+  local ini_file="$1"
+
+  local current_section=""
+  local has_free_keys=false
+
+  rm -f "$ini_file"
+
+  for key in $(ini_keys); do
+    [[ $key == *.* ]] && continue
+    has_free_keys=true
+    value="${ini[$key]}"
+    echo "$key = $value" >>"$ini_file"
+  done
+
+  [[ "${has_free_keys}" == "true" ]] && echo >>"$ini_file"
+
+  for key in $(ini_keys); do
+    [[ $key == *.* ]] || continue
+    value="${ini[$key]}"
+    IFS="." read -r section_name key_name <<<"$key"
+
+    if [[ "$current_section" != "$section_name" ]]; then
+      [[ $current_section ]] && echo >>"$ini_file"
+      echo "[$section_name]" >>"$ini_file"
+      current_section="$section_name"
+    fi
+
+    echo "$key_name = $value" >>"$ini_file"
+  done
+}
+
+ini_show() {
+  declare -gA ini
+
+  for key in $(ini_keys); do
+    echo "$key = ${ini[$key]}"
+  done
+}
+
+ini_keys() {
+  declare -gA ini
+
+  local keys=("${!ini[@]}")
+  for a in "${keys[@]}"; do echo "$a"; done | sort
 }
 
 # src/lib/logger.sh
@@ -1851,8 +1919,6 @@ zcli_config_customers_command() {
 # :command.function
 zcli_config_database_command() {
   # src/config_database_command.sh
-  sleep 10
-
   case ${ZNUNY_DATABASE_TYPE} in
     "mysql")
       if database_check_mysql "${ZNUNY_DATABASE_HOST}" "${ZNUNY_DATABASE_PORT}" "${ZNUNY_DATABASE_NAME}" "${ZNUNY_DATABASE_USER}" "${ZNUNY_DATABASE_PASSWORD}"; then
@@ -1863,6 +1929,14 @@ zcli_config_database_command() {
       fi
     ;;
     "pgsql")
+      customLogger "info" "config_database" "Check the connexion to the PostgreSQL database"
+      if database_wait_pgsql "${ZNUNY_DATABASE_HOST}" "${ZNUNY_DATABASE_PORT}" "${ZNUNY_DATABASE_NAME}" "${ZNUNY_DATABASE_USER}" "${ZNUNY_DATABASE_PASSWORD}"; then
+        customLogger "info" "config_database" "The PostgreSQL database is available"
+      else
+        customLogger "error" "config_database" "The PostgreSQL database is missing"
+        exit 1
+      fi
+
       if database_check_pgsql "${ZNUNY_DATABASE_HOST}" "${ZNUNY_DATABASE_PORT}" "${ZNUNY_DATABASE_NAME}" "${ZNUNY_DATABASE_USER}" "${ZNUNY_DATABASE_PASSWORD}"; then
         customLogger "warn" "config_database" "SKIP: The database is not empty"
       else
@@ -2084,7 +2158,7 @@ zcli_init_command() {
 
   zcli user admin
 
-  # zcli dev
+  # # zcli dev
 
   zcli run znuny
 
